// Code generated by "stringer -type=Language"; DO NOT EDIT.

package lingua

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Chinese-0]
	_ = x[English-1]
	_ = x[French-2]
	_ = x[German-3]
	_ = x[Italian-4]
	_ = x[Japanese-5]
	_ = x[Korean-6]
	_ = x[Portuguese-7]
	_ = x[Russian-8]
	_ = x[Spanish-9]
	_ = x[Unknown-10]
}

const _Language_name = "ChineseEnglishFrenchGermanItalianJapaneseKoreanPortugueseRussianSpanishUnknown"

var _Language_index = [...]uint8{0, 7, 14, 20, 26, 33, 41, 47, 57, 64, 71, 78}

func (i Language) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Language_index)-1 {
		return "Language(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Language_name[_Language_index[idx]:_Language_index[idx+1]]
}
